name: aqua
description: install packages using aqua
inputs:
  config:
    description: path to config
    required: true
    default: ${{ github.workspace }}/aqua.yaml
  version:
    description: aqua version
    required: true
    default: v0.7.9 # renovate: depName=suzuki-shunsuke/aqua
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
runs:
  using: "node12"
  main: "dist/index.js"
