name: aqua
description: install packages using aqua
inputs:
  config:
    description: path to config
    required: true
    default: ${{ github.workspace }}/aqua.yaml
  version:
    description: aqua version
    required: true
    default: v0.8.1 # renovate: depName=aquaproj/aqua
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
runs:
  using: "node12"
  main: "dist/index.js"
