name: ts

on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - aqua.yaml
      - .github/workflows/ts.yaml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - aqua.yaml
      - .github/workflows/ts.yaml

jobs:
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - uses: ./
      - run: find ~/.aqua

      # https://github.com/suzuki-shunsuke/github-comment
      - run: github-comment exec -- echo e2e-test passed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
