name: ts

on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

jobs:
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn format-check
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - uses: ./
      - run: find ~/.aqua

      # https://github.com/suzuki-shunsuke/github-comment
      - run: github-comment exec -- echo e2e-test passed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
